### ISSUE TITLE
profile:generate fails with Error: Class ‘Drutiny\ProfileInformation’ not found

### ISSUE THREAD

**Issue by seanhamlin** [seanhamlin/site-audit#171]
This command fails with a 

```
./vendor/bin/drutiny profile:generate
Please provide a title for your profile: xena
Please provide a machine name for your profile: xena
Add policies you would like added to this profile:
> Test:Fail
Add another policy or <enter> to finish: 
PHP Fatal error:  Uncaught Error: Class ‘Drutiny\ProfileInformation’ not found in /Users/adama.zoumanigui/GitHub/ucla/vendor/drutiny/drutiny/src/Command/ProfileGenerateCommand.php:58
Stack trace:
#0 /Users/adama.zoumanigui/GitHub/ucla/vendor/symfony/console/Command/Command.php(252): Drutiny\Command\ProfileGenerateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /Users/adama.zoumanigui/GitHub/ucla/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/adama.zoumanigui/GitHub/ucla/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Drutiny\Command\ProfileGenerateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/adama.zoumanigui/GitHub/ucla/vendor/symfony/console/Application. in /Users/adama.zoumanigui/GitHub/ucla/vendor/drutiny/drutiny/src/Command/ProfileGenerateCommand.php on line 58

Fatal error: Uncaught Error: Class ‘Drutiny\ProfileInformation’ not found in /Users/adama.zoumanigui/GitHub/ucla/vendor/drutiny/drutiny/src/Command/ProfileGenerateCommand.php on line 58

Error: Class ‘Drutiny\ProfileInformation’ not found in /Users/adama.zoumanigui/GitHub/ucla/vendor/drutiny/drutiny/src/Command/ProfileGenerateCommand.php on line 58
```

**Comment by fiasco** [comment]
Ah yeah, `ProfileInformation` was removed in `2.1.x` but its still there is `2.0.x` if you want to use `profile:generate` now.

generating audits and profiles does not currently work on 2.1.x and needs to be addressed.

**Comment by seanhamlin** [comment]
So what should the default installation be for people now? I would assume 2.1.1 seeing as this is the latest tag. We also need to update the install docs to say this. I believe Adama is keen to help out here.

**Comment by fiasco** [comment]
2.1.1 is the default atm. I've not really considered *:generate commands apart of core stability as they're not documented or included in the travis build. Buts not to say we shouldn't make them 1st class citizens. Especially if it helps people build profiles (to which https://drutiny.github.io/2.1.x/profiles/ is also available and arguably a better resource).

**Comment by fiasco** [comment]
Drutiny 2.1.x now supports profile:generate and audit:generate.
