### ISSUE TITLE
Task remediation method `check` is missing.

### ISSUE THREAD

**Issue by fubarhouse** [seanhamlin/site-audit#217]
**Composer Info**
```
caseyamcl/toc                         v1.2    Simple Table-of-Contents Generator for PHP.  Generates TOCs based off H1...H6 tags
cocur/slugify                         v1.4.1  Converts a string into a slug.
composer/semver                       1.4.2   Semver library that offers utilities, version constraint parsing and validation.
doctrine/annotations                  v1.6.0  Docblock Annotations Parser
doctrine/lexer                        v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
drutiny/drutiny                       2.3.1   This is a generic Drupal 7 and Drupal 8 site auditing and optional remediation tool.
drutiny/http                          2.4     Drutiny auditing and policies on HTTP requests
drutiny/plugin-drupal-7               2.1     Drupal 7 plugin for Drutiny
drutiny/plugin-drupal-8               2.1     Drupal 8 plugin for Drutiny
erusev/parsedown                      1.7.1   Parser for Markdown.
fiasco/symfony-console-style-markdown 1.0     A Symfony Console Style extension to support Markdown formatting.
guzzlehttp/guzzle                     6.3.3   Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1  Guzzle promises library
guzzlehttp/psr7                       1.4.2   PSR-7 message implementation that also provides common utility methods
kevinrob/guzzle-cache-middleware      v3.2.1  A HTTP/1.1 Cache for Guzzle 6. It's a simple Middleware to be added in the HandlerStack. (RFC 7234)
knplabs/knp-menu                      2.3.0   An object oriented menu library
masterminds/html5                     2.3.0   An HTML5 parser and serializer.
mustache/mustache                     v2.12.0 A Mustache implementation in PHP.
paragonie/random_compat               v2.0.17 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
psr/cache                             1.0.1   Common interface for caching libraries
psr/http-message                      1.0.1   Common interface for HTTP messages
psr/log                               1.0.2   Common interface for logging libraries
psr/simple-cache                      1.0.1   Common interfaces for simple caching
romaricdrigon/metayaml                1.1     Using [Yaml|Xml|json] schemas files to validate [Yaml|Xml|json]
symfony/cache                         v3.4.17 Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader                  v3.4.17 Symfony ClassLoader Component
symfony/console                       v3.4.17 Symfony Console Component
symfony/debug                         v4.1.6  Symfony Debug Component
symfony/expression-language           v3.4.17 Symfony ExpressionLanguage Component
symfony/finder                        v3.4.17 Symfony Finder Component
symfony/polyfill-apcu                 v1.9.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype                v1.9.0  Symfony polyfill for ctype functions
symfony/polyfill-mbstring             v1.9.0  Symfony polyfill for the Mbstring extension
symfony/process                       v3.4.17 Symfony Process Component
symfony/translation                   v4.1.6  Symfony Translation Component
symfony/validator                     v3.4.17 Symfony Validator Component
symfony/yaml                          v3.4.17 Symfony Yaml Component
twig/twig                             v1.35.4 Twig, the flexible, fast, and secure template language for PHP
```

**PHP Info**
```
PHP 7.1.23 (cli) (built: Oct 15 2018 20:17:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.23, Copyright (c) 1999-2018, by Zend Technologies
```

**To Reproduce**
The command run to produce the error:
```
drutiny profile:run ci @self -r
```

**Error output**

```
 12/55 [===>--------------]  21% 8.0 MiBPHP Fatal error:  Uncaught Error: Call to undefined method Drutiny\Plugin\Drupal7\Audit\ModuleDisabled::check() in /app/sites/all/drutiny/vendor/drutiny/plugin-drupal-7/src/Audit/ModuleDisabled.php:49
Stack trace:
#0 /app/sites/all/drutiny/vendor/drutiny/drutiny/src/Sandbox/Sandbox.php(142): Drutiny\Plugin\Drupal7\Audit\ModuleDisabled->remediate(Object(Drutiny\Sandbox\Sandbox))
#1 /app/sites/all/drutiny/vendor/drutiny/drutiny/src/Assessment.php(63): Drutiny\Sandbox\Sandbox->remediate()
#2 /app/sites/all/drutiny/vendor/drutiny/drutiny/src/Command/ProfileRunCommand.php(258): Drutiny\Assessment->assessTarget(Object(Drutiny\Target\DrushTarget), Array, Object(DateTime), Object(DateTime), true)
#3 /app/sites/all/drutiny/vendor/symfony/console/Command/Command.php(255): Drutiny\Command\ProfileRunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /app/sites/all/drutiny/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(O in /app/sites/all/drutiny/vendor/drutiny/plugin-drupal-7/src/Audit/ModuleDisabled.php on line 49
```

**Expected behavior**
Drutiny is expected to make an attempt to remediate the problem when instructed to with the use of the `r` flag. Without this flag it does not provide a stack trace or remediate it and with the flag it does not complete, remediate or not produce a stack trace.

It is expected to have the method to call to.

**Screenshots**
![image](https://user-images.githubusercontent.com/3070264/50672696-dd119300-102d-11e9-9363-bc5214510a83.png)

![image](https://user-images.githubusercontent.com/3070264/50672792-41345700-102e-11e9-8a9c-55440592624c.png)

![image](https://user-images.githubusercontent.com/3070264/50673113-f9163400-102f-11e9-9fbb-6926e92ba8e8.png)

**Additional context**
Note the error `Uncaught Error: Call to undefined method Drutiny\Plugin\Drupal7\Audit\ModuleDisabled::check() in /app/sites/all/drutiny/vendor/drutiny/plugin-drupal-7/src/Audit/ModuleDisabled.php:49` states the missing method `check` missing in `ModuleDisabled.php`.

Reference: https://github.com/drutiny/plugin-drupal-7/blob/2.x/src/Audit/ModuleDisabled.php

`ModuleDisabled` extends `Audit` as described in the second screenshot and the structure of the `Audit` class simply does not have a `check()` method.

When an empty function to return a boolean is included, the functionality works. If `check()` returns `TRUE` it will remediate the issues identified as expected. If the method returns `FALSE`, nothing happens despite the `remediate()` method actually remediating the item - so the method returning false actually invalidates the `remediate()` method.

**Comment by fiasco** [comment]
If you change it from `check` to `audit` then it should work. This will be a legacy breakage from the 1.x architecture (remediation doesn't get as much attention as it should). If that works, please file a PR!

**Comment by fubarhouse** [comment]
@fiasco,

Thanks for the heads up. That's working, so I'll submit a PR for Drutiny, and the 7 & 8 plugins.

**Comment by fubarhouse** [comment]
See #218, https://github.com/drutiny/plugin-drupal-8/pull/18 and https://github.com/drutiny/plugin-drupal-7/pull/7
