### ISSUE TITLE
drutiny `2.4.*@dev` no longer requires drutiny/http plugin, breaking drutinycs

### ISSUE THREAD

**Issue by briantully** [seanhamlin/site-audit#236]
**Composer Info**
```
running standalone phar drutinycs 3.0-beta3
```

**PHP Info**
```
PHP 7.2.24 (cli) (built: Oct 25 2019 11:14:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24, Copyright (c) 1999-2018, by Zend Technologies
```

**To Reproduce**
The command run to produce the error:
```
using drutinycs 3.0-beta3 or drutiny 2.4.x run a profile that includes policies for drutiny/http
```

**Error output**

```
PHP Fatal error:  Uncaught Error: Call to a member function hasHeader() on null in phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Http/Audit/HttpHeaderExists.php:37
Stack trace:
#0 phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Http/Audit/HttpHeaderNotExists.php(29): Drutiny\Http\Audit\HttpHeaderExists->audit(Object(Drutiny\Sandbox\Sandbox))
#1 phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Audit.php(76): Drutiny\Http\Audit\HttpHeaderNotExists->audit(Object(Drutiny\Sandbox\Sandbox))
#2 phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Sandbox/Sandbox.php(94): Drutiny\Audit->execute(Object(Drutiny\Sandbox\Sandbox))
#3 phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Assessment.php(62): Drutiny\Sandbox\Sandbox->run()
#4 phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Command/ProfileRunCommand.php(234): Drutiny\Assessment->assessTarget(Object(Drutiny\Acquia\CS\Target\Aht in phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Http/Audit/HttpHeaderExists.php on line 37

Fatal error: Uncaught Error: Call to a member function hasHeader() on null in phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Http/Audit/HttpHeaderExists.php:37
Stack trace:
#0 phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Http/Audit/HttpHeaderNotExists.php(29): Drutiny\Http\Audit\HttpHeaderExists->audit(Object(Drutiny\Sandbox\Sandbox))
#1 phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Audit.php(76): Drutiny\Http\Audit\HttpHeaderNotExists->audit(Object(Drutiny\Sandbox\Sandbox))
#2 phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Sandbox/Sandbox.php(94): Drutiny\Audit->execute(Object(Drutiny\Sandbox\Sandbox))
#3 phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Assessment.php(62): Drutiny\Sandbox\Sandbox->run()
#4 phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Command/ProfileRunCommand.php(234): Drutiny\Assessment->assessTarget(Object(Drutiny\Acquia\CS\Target\Aht in phar:///Users/brian.tully/Dropbox/bin/drutinycs/vendor/drutiny/drutiny/src/Http/Audit/HttpHeaderExists.php on line 37
```

**Expected behavior**
A report generated without fatal errors.

**Screenshots**

**Additional context**
drutiny 2.4.x seems to have removed drutiny/http plugin from requirements in composer.json, resulting in many profiles failing due to fatal errors since http plugin is not found.

**Comment by briantully** [comment]
hmm it seems that drutiny/http was removed as an external dependency and added to the project src folder a few months back in commit https://github.com/drutiny/drutiny/commit/9c366f390a5b9c1c27bfa0ac0ba1f95c3cf0b850#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

I cleared cache `drutinycs cache:clear` but that didn't fix it. I'll try manually deleting the `~/.drutiny/cache/*` directories

**Comment by briantully** [comment]
Disregard. PEBCAK :P
