### ISSUE TITLE
Uncaught Error: Call to a member function drush() on null

### ISSUE THREAD

**Issue by bschilt** [seanhamlin/site-audit#254]
I'm creating a new policy that leverages the IniGet class. When running the policy, the error below is produced. 

**To Reproduce**
The command run to produce the error:
There are currently no policies that leverage the IniGet Class so a command is not available. 

**Error output**

```
Notice: Undefined property: Drutiny\Audit\Drupal\IniGet::$sandbox in /Users/brian.schilt/GIT/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Audit/Drupal/IniGet.php on line 34
PHP Fatal error:  Uncaught Error: Call to a member function drush() on null in /Users/brian.schilt/GIT/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Audit/Drupal/IniGet.php:34
Stack trace:
#0 /Users/brian.schilt/GIT/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Audit.php(76): Drutiny\Audit\Drupal\IniGet->audit(Object(Drutiny\Sandbox\Sandbox))
#1 /Users/brian.schilt/GIT/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Sandbox/Sandbox.php(94): Drutiny\Audit->execute(Object(Drutiny\Sandbox\Sandbox))
#2 /Users/brian.schilt/GIT/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Assessment.php(62): Drutiny\Sandbox\Sandbox->run()
#3 /Users/brian.schilt/GIT/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Command/PolicyAuditCommand.php(127): Drutiny\Assessment->assessTarget(Object(Drutiny\Acquia\CS\Target\Aht), Array, Object(DateTime), Object(DateTime), false)
#4 /Users/brian.schilt/GIT/drutiny-cs-adaptor/vendor/symfony/console/Command/Command.php(255): Drutiny\Command\PolicyAuditCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput) in /Users/brian.schilt/GIT/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Audit/Drupal/IniGet.php on line 34
```

**Comment by fiasco** [comment]
Not sure how this got in, but thanks for fixing it!
