### ISSUE TITLE
[Bug] ConfigAnalysis class setting object instead of array

### ISSUE THREAD

**Issue by omkar-pednekar** [seanhamlin/site-audit#311]
Class: `Drutiny\Plugin\Drupal8\Audit\ConfigAnalysis`

Error:
```
Unable to get an item of non-array &quot;config&quot;.
#0 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/symfony/expression-language/Node/BinaryNode.php(90): Symfony\Component\ExpressionLanguage\Node\GetAttrNode-&gt;evaluate(Array, Array)
#1 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/symfony/expression-language/ExpressionLanguage.php(67): Symfony\Component\ExpressionLanguage\Node\BinaryNode-&gt;evaluate(Array, Array)
#2 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Audit.php(187): Symfony\Component\ExpressionLanguage\ExpressionLanguage-&gt;evaluate(&#039;config[&#039;sendmai...&#039;, Array)
#3 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Audit/AbstractAnalysis.php(92): Drutiny\Audit-&gt;evaluate(&#039;config[&#039;sendmai...&#039;, &#039;expression_lang...&#039;)
#4 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Audit.php(131): Drutiny\Audit\AbstractAnalysis-&gt;audit(Object(Drutiny\Sandbox\Sandbox))
#5 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Assessment.php(109): Drutiny\Audit-&gt;execute(Object(Drutiny\Policy), false)
#6 [internal function]: Drutiny\Assessment-&gt;Drutiny\{closure}()
#7 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/fiasco/async/src/Fork.php(67): call_user_func(Object(Closure))
#8 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/fiasco/async/src/ForkManager.php(85): Async\Fork-&gt;run(Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/fiasco/async/src/ForkManager.php(74): Async\ForkManager-&gt;processQueue()
#10 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Assessment.php(110): Async\ForkManager-&gt;run(Object(Closure))
#11 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Console/Command/PolicyAuditCommand.php(136): Drutiny\Assessment-&gt;assessTarget(Object(Drutiny\Acquia\CS\Target\Aht), Array, Object(DateTime), Object(DateTime), false)
#12 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/symfony/console/Command/Command.php(298): Drutiny\Console\Command\PolicyAuditCommand-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/symfony/console/Application.php(1033): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Console/Application.php(93): Symfony\Component\Console\Application-&gt;doRunCommand(Object(Drutiny\Console\Command\PolicyAuditCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/symfony/console/Application.php(299): Drutiny\Console\Application-&gt;doRunCommand(Object(Drutiny\Console\Command\PolicyAuditCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Console/Application.php(61): Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/symfony/console/Application.php(171): Drutiny\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/drutiny/drutiny/stub.php(43): Symfony\Component\Console\Application-&gt;run()
#19 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/drutiny/drutiny/bin/drutiny(3): require_once(&#039;/Users/omkar/Pr...&#039;)
#20 /Users/omkar/Projects/drutiny-cs-adaptor/vendor/bin/drutiny(112): include(&#039;/Users/omkar/Pr...&#039;)
#21 {main}
```

If I print $config, I get below:
```
class Drutiny\Target\Service\_helper#9077 (2) {
  protected $cmd =>
  string(122) "/usr/local/bin/drush-launcher config:get 'swiftmailer.transport' --format='json' --include-overridden --root='$DRUSH_ROOT'"
  protected $service =>
  class Drutiny\Acquia\CS\Service\AhtRemoteService#9697 (2) {
    protected $local =>
    class Drutiny\Target\Service\LocalService#2689 (4) {
      protected $target =>
      class Drutiny\Acquia\CS\Target\Aht#9831 (8) {
        ...
      }
      protected $isWin =>
      bool(false)
      protected $cache =>
      class Symfony\Component\Cache\Adapter\FilesystemAdapter#2672 (13) {
        ...
      }
      protected $logger =>
      class Monolog\Logger#2645 (6) {
        ...
      }
    }
    protected $sshConfig =>
    array(1) {
      'aht.host' =>
      string(33) "ded-15761.prod.hosting.acquia.com"
    }
  }
}
```

**Comment by omkar-pednekar** [comment]
After converting to array, we get output in below format:
```
array(10) {
  'transport' =>
  string(8) "sendmail"
  'smtp_host' =>
  string(9) "127.0.0.1"
  'smtp_port' =>
  int(25)
  'smtp_encryption' =>
  string(0) ""
  'smtp_credential_provider' =>
  string(11) "swiftmailer"
  'smtp_credentials' =>
  array(2) {
    'swiftmailer' =>
    array(2) {
      'username' =>
      string(0) ""
      'password' =>
      string(0) ""
    }
    'key' =>
    array(2) {
      'username' =>
      string(0) ""
      'password' =>
      string(0) ""
    }
  }
  'sendmail_path' =>
  string(18) "/usr/sbin/sendmail"
  'sendmail_mode' =>
  string(1) "t"
  'spool_directory' =>
  string(0) ""
  '_core' =>
  array(1) {
    'default_config_hash' =>
    string(43) "0dJfQivKgyEp-S8D6gSRTBbpRFApE3VkpltnPMBQ5OY"
  }
}
```

**Comment by omkar-pednekar** [comment]
Closing this issue as we don't need to handle this in audit class. We can access object and required properties in policy.
